name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs at midnight every day
  workflow_dispatch: # Allows you to run it manually
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: HiranGeeth
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Colombo # Set to your local time
          plugin_languages: yes
          plugin_languages_ignored: html, css # Keeps the percentages focused on logic code
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
